### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by Phoenix4O4** [marte26/pterodactyl-byond#1]
Greetings, sorry to distract you, I've been trying to set up the configuration to run beestation for some time, but it doesn't work. Could you share a JSON configuration file? I will be very grateful!
Completely desperate :C
@marte26

**Comment by Phoenix4O4** [comment]
Thank you very much!
But :C

saving goonstation.dmb (DEBUG mode)
goonstation.dmb - 0 errors, 0 warnings (10/18/21 1:24 pm)
Total time: 0:44

[Pterodactyl Daemon]: Checking server disk space usage, this could take a
few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this
could take a few seconds...
***@***.***~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few
minutes to complete...
Pulling from marte26/pterodactyl-byond
Digest:
sha256:a391bbe3f707626e9dcf5542c17649cfe11341ba7b118d2c0f1fed007ba4c80c
Status: Image is up to date for marte26/pterodactyl-byond:latest
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./start.sh goonstation.dmb 1355 -trusted -threads on
/entrypoint.sh: line 9: ./start.sh: No such file or directory
***@***.***~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed
state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a
few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this
could take a few seconds...

пн, 18 окт. 2021 г. в 14:00, marte26 ***@***.***>:

**Comment by Phoenix4O4** [comment]
I have already fixed it, there was an incorrect startup command in my file,
I deleted it start.sh Thank you again =)

пн, 18 окт. 2021 г. в 14:00, marte26 ***@***.***>:

**Comment by Phoenix4O4** [comment]
I am very grateful to you, the last question, do you know if this is
normal? Or is there any way to fix it?
[image: image.png]

пн, 18 окт. 2021 г. в 14:00, marte26 ***@***.***>:

**Comment by marte26** [comment]
I can't see the image

**Comment by marte26** [comment]
You should also try downloading the updated egg from the repo

**Comment by marte26** [comment]
I fixed some stuff that wasn't working

**Comment by Phoenix4O4** [comment]
Do you happen to have an egg for tgstation?

пн, 18 окт. 2021 г. в 14:00, marte26 ***@***.***>:

**Comment by marte26** [comment]
No sorry I only have one for Goonstation
